import sys
import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

# Initialize the OpenAI client
def get_openai_client():
    """
    Initializes the OpenAI client with a check for the API key.

    Returns:
        OpenAI: An instance of the OpenAI client ready for making API calls.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    
    if not api_key:
        print("\n ERROR: OPENAI_API_KEY not found in environment")
        print("Please ensure you have a .env file with your key set")
        print("See .env.example for the required format\n")

        sys.exit(1)

    return OpenAI(api_key=api_key)

def generate_sql(user_query: str, system_prompt: str):
    """
    Sends the generated prompt to the LLM and returns cleaned SQL.

    Args:
        user_query (str): The original natural language query from the user.
        system_prompt (str): The system instructions for the LLM based on the routed table.

    Returns:
        str: The SQL query generated by the LLM, cleaned of any markdown formatting.
    """
    try:
        client = get_openai_client()
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_query}
            ],
            temperature=0
        )

        sql_output = response.choices[0].message.content.strip()

        # Post-processing: 
        # Remove markdown backticks if the LLM included them
        if sql_output.startswith("```"):
            # Splits by newline and take the middle content
            sql_output = sql_output.split("\n", 1)[1].rsplit("\n", 1)[0].strip()
            # Remove "sql" language identifier if present
            if sql_output.lower().startswith("sql"):
                sql_output = sql_output[3:].strip()

        return sql_output

    except Exception as e:
        print(f"Error during LLM inference: {e}")
        return None