from src.database import execute_query

CENSUS_GUARDRAIL_PROMPT = """You are a topic classifier for a US Census data assistant.
Determine if the following question is related to US Census demographics data, OR is a follow-up 
to a census-related conversation.
Census topics include: population, income, age, race, gender, education, housing, 
employment, poverty, commute, language, health insurance.

A question is VALID if ANY of these are true:
- It asks about census demographics directly
- It mentions a US location (state, county, city)
- It mentions a year (2019, 2020)
- It is a short follow-up phrase like "what about X", "how about", "and for", "compare", "in 2019", "what about TX"

A question is INVALID only if it is clearly completely unrelated to census data
(e.g. cooking recipes, sports scores, personal questions like "what is your name").
Respond with ONLY one word: "VALID" or "INVALID"
Question: {query}"""


def is_census_related(query: str) -> bool:
    """
    Uses Snowflake Cortex to determine if the user's query is related to US Census data.
    This guardrail helps prevent irrelevant or off-topic queries from being processed.

    Args:
        query (str): The natural language query from the user.

    Returns:
        bool: True if the query is related to Census data (VALID), False otherwise (INVALID)
    """
    prompt = CENSUS_GUARDRAIL_PROMPT.format(query=query.replace("'", "''"))
    cortex_sql = (
        f"SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-7b', '{prompt}') AS verdict"
    )

    try:
        result_df = execute_query(cortex_sql)
        verdict = result_df.iloc[0, 0].strip().upper()
        return verdict.startswith("VALID")
    except Exception as e:
        print(f"Guardrail check failed: {e}")
        return True


def clean_sql(raw_sql: str) -> str:
    """
    Cleans the raw SQL output from the LLM by removing unwanted characters and formatting issues.

    Args:
        raw_sql (str): The raw SQL string generated by the LLM.
    Returns:
        str: The cleaned SQL string ready for execution.
    """
    if raw_sql:
        # Handle the literal \n characters
        clean_sql = raw_sql.replace("\\n", "\n")

        # Remove any JSON-style wrapping quotes
        clean_sql = clean_sql.strip().strip('"').strip("'")

        # Convert escaped quotes \" to "
        clean_sql = clean_sql.replace('\\"', '"')

        # Remove Markdown backticks
        clean_sql = clean_sql.replace("```sql", "").replace("```", "")
        return clean_sql.strip()

    return None


def generate_sql(user_query: str, system_prompt: str) -> str:
    """
    Uses Snowflake Cortex to generate SQL. No external API key needed

    Args:
        user_query (str): The natural language query from the user.
        system_prompt (str): The system instructions for the LLM based on the routed table.

    Returns:
        str: The generated SQL query from the LLM.
    """

    # Combine the instructions and the query
    prompt = str(system_prompt) + "\n\nUser Question: " + str(user_query)

    # Sanitize the prompt to escape single quotes for safe SQL embedding.
    sanitized_prompt = prompt.replace("'", "''")

    # Using 'mistral-large2' model for SQL generation, which is optimized for code tasks.
    # The COMPLETE function will return the generated SQL directly.
    cortex_sql = (
        f"SELECT SNOWFLAKE.CORTEX.AI_COMPLETE('mistral-large2', '{sanitized_prompt}')"
    )

    try:
        # 1. Execute the Cortex AI_COMPLETE call
        result_df = execute_query(cortex_sql)
        raw_sql = result_df.iloc[0, 0]

        # 2. Clean the raw SQL output
        cleaned_sql = clean_sql(raw_sql)
        return cleaned_sql
    except Exception as e:
        print(f"Cortex Inference Error: {e}")
        return None
